### ISSUE TITLE
Little help for byteArray value...

### ISSUE THREAD

**Issue by Stortof** [kemsky/air-hid-usb#2]
-----------------------------------------------------------------------
Edit : OK I found a solution :) you can close this post.
-----------------------------------------------------------------------

Hi Kemsky and thanks for sharing your work :)

I am not an expert in binary and I need a little help because I c'ant fin any AS3 resources on how to read data from HID devices.

My main problem is that I don't' know witch byteArray I need to pass to the read function.
If I understand, the first byte must match the report ID...
```
_ba = new ByteArray();
_ba.writeByte(0x1);
trace(_device.read(_ba));
```
But I always get "10" on return.

I need to get the "Ry" value (rotation) that is in red on this screen capture...

![hid](https://cloud.githubusercontent.com/assets/1485673/6057531/4e328e34-ad1f-11e4-98f5-d50b6f8b7f9c.jpg)

Well, I am lost...do you have any example or explanation on how to make the AS3 byteArray and HID Devices compatible ?

Best regards.

**Comment by kemsky** [comment]
Hi, you can share your results with others :)
