### ISSUE TITLE
Documentation link redirects to a new site & How to generate a android ANE

### ISSUE THREAD

**Issue by foreverpinetree** [kemsky/air-hid-usb#3]
Hello, the documentation link is not available, and how to generate a android ANE?

**Comment by kemsky** [comment]
Hello, android extension was not completed, so only OS X and Windows.

**Comment by foreverpinetree** [comment]
OK, thanks for your reply, do you have a plan to finish it?

**Comment by kemsky** [comment]
No, i don't think so, you can use classes from [code.google.com](https://code.google.com/p/air-hid-usb/source/browse/#svn%2Ftrunk%2Fhidapi%2Fhidapi_native%2Fandroid%2Fsrc%2Fcom%2Fhidapi) to implement android part. As i remember, native part of extension on android is just simple android library.
